export const GYM_QUOTES: string[] = [
  "El dolor que sientes hoy es la fuerza que sentirás mañana.",
  "No pares cuando duela. Para cuando termines.",
  "La única mala sesión es la que no hiciste.",
  "Tu cuerpo puede soportar casi cualquier cosa. Es tu mente la que debes convencer.",
  "El músculo no crece en la comodidad.",
  "Sudar es la grasa llorando.",
  "Levántate. Entrena. Repite. Domina.",
  "No tienes que ser grande para empezar, pero tienes que empezar para ser grande.",
  "El hierro nunca miente.",
  "Cada repetición te acerca a quien quieres ser.",
  "El gym no construye carácter, lo revela.",
  "Si todavía puedes respirar, todavía puedes seguir.",
  "Dolor temporal, orgullo eterno.",
  "La disciplina vencerá al talento cuando el talento no sea disciplinado.",
  "Entrena como si nadie estuviera mirando.",
  "Las pesas no mienten. Los resultados tampoco.",
  "Tu único límite eres tú.",
  "Aprieta los dientes y carga.",
  "No hay atajos. Solo hierro y sudor.",
  "Lo que haces cuando nadie mira es lo que te define.",
  "Ganar no es un destino, es un estilo de vida.",
  "Piernas que tiemblan, mente que crece.",
  "Cada gota de sudor es un paso hacia adelante.",
  "El que entrena con dolor, compite sin piedad.",
  "Fortalece tu cuerpo, fortalece tu mente.",
  "No entrenas para verte bien. Entrenas para ser imparable.",
  "El músculo se gana con lágrimas y sudor, no con excusas.",
  "Si no desafías tu cuerpo, nunca cambiará.",
  "El éxito es la suma de pequeñas decisiones repetidas.",
  "Transforma el dolor en poder.",
  "Haz que cada serie cuente.",
  "Ríndete cuando mueras. Hasta entonces, carga.",
  "La máquina más poderosa del gym está entre tus orejas.",
  "No se trata de ser el más fuerte. Se trata de ser más fuerte que ayer.",
  "Nunca sabrás de lo que eres capaz hasta que lo intentes.",
  "El gym es terapia con hierro.",
  "Respira hondo. Carga más. Repite.",
  "Sin disciplina, el talento es solo potencial.",
  "Los únicos límites son los que tú mismo te pones.",
  "Fracasar en una repetición es mejor que fracasar en intentarlo.",
  "Hazlo por ti. No por nadie más.",
  "Suda más hoy, brilla más mañana.",
  "Nada que valga la pena es fácil.",
  "Conviértete en la persona que tu yo del pasado admiraría.",
  "Un día sin entrenar es un día perdido.",
  "La incomodidad es el precio del crecimiento.",
  "Tu mentalidad es tu mayor músculo.",
  "Sueña en grande. Carga más pesado.",
  "El gimnasio no te da nada. Te quita las excusas.",
  "Mientras otros duermen, tú construyes.",
  "Ser fuerte no es una opción, es una obligación.",
  "Donde termina tu zona de confort, empieza tu verdadero potencial.",
  "No hay día malo para entrenar. Hay días duros y días más duros.",
  "El peso no sabe quién eres. Solo sabe cuánto puedes.",
  "Si quieres algo que nunca has tenido, haz algo que nunca has hecho.",
  "Sin dolor no hay ganancia.",
  "La mejor versión de ti está en construcción.",
  "Domina tu cuerpo, domina tu vida.",
  "No esperes a estar motivado. Entrena y la motivación llegará.",
  "Las excusas no construyen músculo.",
  "El carácter se forja en la repetición.",
  "Lo difícil es lo que te hace crecer.",
  "Aguanta 5 segundos más. Esos 5 segundos lo cambian todo.",
  "No hay hechizos mágicos. Solo constancia.",
  "Entrena con propósito, no con prisa.",
  "La debilidad abandona el cuerpo cuando la mente se niega a rendirse.",
  "Cada fracaso en el gym es una lección disfrazada.",
  "Las ruedas no se inventaron en un día. Tus abs tampoco.",
  "Vístete, sal, entrena. No pienses. Hazlo.",
  "El gym es el único lugar donde cargar más peso es una victoria.",
  "La fuerza no viene de lo que puedes hacer. Viene de superar lo que creías que no podías.",
  "Confía en el proceso. Respeta el dolor.",
  "Enfócate en el progreso, no en la perfección.",
  "La disciplina duele menos que el arrepentimiento.",
  "Deja de buscar atajos. No existen.",
  "Cada serie rechazada es una debilidad superada.",
  "El dolor es temporal, la gloria es para siempre.",
  "Un campeón entrena cuando nadie mira.",
  "No te compares. Compite contigo mismo.",
  "Tu cuerpo es el templo de tu mente. Constrúyelo.",
  "Entrena con furia. Vive con calma.",
  "Nunca es demasiado tarde para empezar. Siempre es demasiado pronto para rendirse.",
  "El gimnasio te acepta tal como eres y te transforma en lo que puedes ser.",
  "Rómpete a ti mismo. Reconstrúyete. Repite.",
  "No se trata de cuánto levantas. Se trata de quién te conviertes.",
  "Los días malos existen. Pero peor es no haber ido.",
  "Haz que el espejo sea tu competencia.",
  "La grandeza no se hereda. Se levanta. Se carga. Se suda.",
  "Si duele, es porque está funcionando.",
  "Cada mañana tienes la oportunidad de ser mejor.",
  "La diferencia entre lo ordinario y lo extraordinario es ese pequeño extra.",
  "No te rindas. El principio siempre es lo más difícil.",
  "El músculo te recuerda quién eres cada mañana al despertar.",
  "Tus ídolos también empezaron desde cero.",
  "El fitness no es un destino, es un camino sin fin.",
  "Construye un cuerpo que tu mente merezca.",
  "No entrenas por estética. Entrenas por respeto propio.",
  "El sudor es solo la grasa llorando.",
  "Pesado es el arrepentimiento. Liviano es el orgullo.",
  "La barra no te juzga. Solo te reta.",
  "Haz más de lo que te pidieron. Sé más de lo que esperaban.",
  "Préndele fuego a tus límites.",
  "Ser ordinario es una elección. Ser extraordinario también.",
  "El que disfruta el proceso, domina el resultado.",
  "Entrena en silencio. Deja que tus resultados griten.",
  "El dolor de la disciplina pesa kilos. El del arrepentimiento pesa toneladas.",
  "Los sueños no se cumplen, se construyen. Con hierro y sudor.",
  "Tu cuerpo logra lo que tu mente cree.",
  "Conviértete en imparable.",
  "Más series. Menos excusas.",
  "Sin esfuerzo no hay recompensa.",
  "El gym no es un hobby. Es un estilo de vida.",
  "Si te rindes ahora, ¿qué te hace pensar que no lo harás después?",
  "El gimnasio es mi segunda casa. La barra es mi confesor.",
  "Haz del dolor tu combustible.",
  "Disciplina sobre motivación. Siempre.",
  "Cada minuto en el gym es un minuto invertido en ti.",
  "La palabra \"no puedo\" no existe en el diccionario del guerrero.",
  "Los músculos se construyen con paciencia y consistencia.",
  "Prefiero morir de cansancio que de aburrimiento.",
  "Olvida el resultado. Enamórate del proceso.",
  "No hay gloria sin sacrificio.",
  "El gym es mi meditación. El sudor, mi mantra.",
  "No le debes nada a nadie. Pero te lo debes todo a ti mismo.",
  "Si no te duelen las piernas, no entrenaste piernas.",
  "Entrenar sin música es poesía pura.",
  "Cada día es una nueva oportunidad para levantar más.",
  "Si buscas resultados distintos, haz cosas distintas.",
  "Lo que hoy te cuesta, mañana será tu calentamiento.",
  "Domina tu interior. Tu exterior lo reflejará.",
  "El que se rinde no triunfa.",
  "Sudor + disciplina = resultados.",
  "Más pesado. Más fuerte. Más rápido.",
  "Nunca subestimes el poder de una buena sesión de gym.",
  "El respeto se gana en la barra, no en el espejo.",
  "Lo que haces en la oscuridad, brilla a la luz.",
  "El gym no te cambia. Te encuentra.",
  "Querer es poder. Entrenar es hacer.",
  "Hazte adicto al progreso.",
  "Respira fuego. Escupe sudor.",
  "Carga tus miedos. Descarga tus dudas.",
  "Nunca es suficiente. Siempre puedes más.",
  "El que domina su cuerpo, domina su destino.",
  "Lucha contra la gravedad. Gánale.",
  "Las agujetas son medallas de esfuerzo.",
  "Cuando tu cuerpo diga 'no', tu mente debe gritar 'sí'.",
  "La barra te espera. No llegues tarde.",
  "El mejor suplemento es la constancia.",
  "Cada gota de sudor es una debilidad que abandona tu cuerpo.",
  "Seamos realistas: pide lo imposible y carga por ello.",
  "Tu peor enemigo es el espejo. Tu mejor amigo, la barra.",
  "Mata tus excusas antes que ellas maten tus sueños.",
  "El verdadero powerlifting es levantarse cada mañana.",
  "Entrena con el corazón. Carga con el alma.",
  "Sin sacrificio no hay victoria.",
  "Hazlo con miedo, pero hazlo.",
  "Entre el dolor y la nada, elijo el dolor.",
  "Tú contra ti. El único rival que importa.",
  "La mejor terapia cuesta sudor, no dinero.",
  "No te rindas. La próxima repetición te define.",
  "Más que un cuerpo, estás construyendo un carácter.",
  "El único dolor que importa es el del arrepentimiento.",
  "Donde hay voluntad, hay músculo.",
  "Un hombre se mide por lo que carga, no por lo que dice.",
  "Cada serie rechazada es una victoria sobre ti mismo.",
  "Caer está permitido. Rendirse, no.",
  "El verdadero fracaso es no haberlo intentado.",
  "La disciplina es elegir lo que quieres ahora sobre lo que quieres después.",
  "Demuéstrate quién eres. Sé tu propio héroe.",
  "El cambio empieza cuando el dolor de seguir igual supera el dolor de cambiar.",
  "No solo levantas pesas. Levantas tus estándares.",
  "Entrena como un animal. Vive como un rey.",
  "Los imposibles de hoy son los calentamientos de mañana.",
  "Lo que no te desafía, no te cambia.",
  "El gym no es vanidad. Es salud mental.",
  "Entrena, come, duerme, repite.",
  "El descanso es para los débiles. La barra te espera.",
  "Lo que no se entrena, se atrofia.",
  "Carga con orgullo. Descansa con honor.",
  "Si entrenas con el ego, te lesiona. Si entrenas con el corazón, te transforma.",
  "La carga no te define. Cómo la llevas, sí.",
  "Entrar al gym es ganar. Lo demás es bonus.",
  "El músculo es el reflejo de la voluntad.",
  "Entre el sofá y el rack, elige el rack. Siempre.",
  "Suda ahora para que el futuro te lo agradezca.",
  "Actitud de campeón incluso en el calentamiento.",
  "El gym no discrimina. Solo recompensa.",
  "Conviértete en la persona que no necesita motivación.",
  "Hazlo aunque no quieras. Esa es la disciplina.",
  "Tu legado se construye repetición a repetición.",
  "El mejor momento para entrenar fue ayer. El segundo mejor es ahora.",
  "No tienes que ser perfecto. Tienes que ser constante.",
  "El gym es un espejo. No miente.",
  "Entrenar no es un castigo. Es un privilegio.",
  "Agradece poder moverte. Aprovecha cada minuto.",
  "Más fuerte que ayer. Más débil que mañana.",
  "Sin lucha no hay gloria.",
  "Si duele, es bueno. Si tiembla, es mejor.",
  "El gym no se trata de estética. Se trata de respeto propio.",
  "Cada minuto sufriendo es una hora disfrutando.",
  "El cuerpo es el templo. No lo ensucies con excusas.",
  "Hace falta valor para cargar más. Hace falta humildad para bajar el peso.",
  "No compitas. Supérate.",
  "No hay nada más ruidoso que el silencio de un PR logrado.",
  "El gym es mi hábitat natural.",
  "La incomodidad de hoy es la fuerza de mañana.",
  "No se entrena para ser mejor que otros, sino para ser mejor que uno mismo.",
  "Entrenar no es un hábito. Es un instinto.",
  "Respeta la barra. Ella respeta al que se esfuerza.",
  "Deja de lado el teléfono. Agarra la mancuerna.",
  "Hazlo hasta que te duela. Luego haz una más.",
  "El mejor proyecto en el que puedes trabajar eres tú mismo.",
  "El sudor de hoy es el héroe de mañana.",
  "La verdadera fuerza no es levantar más. Es no rendirse nunca.",
  "Un día sin gym es un día sin alma.",
  "Cada repetición es una declaración de guerra contra la mediocridad.",
  "Un hombre vale lo que vale su palabra. Y sus kilos en press banca.",
  "Construye un cuerpo a prueba de excusas.",
  "El verdadero progreso no se ve en el espejo, se siente en el alma.",
  "No se necesitan alas para volar. Se necesitan piernas para saltar más alto.",
  "Domestica la bestia que llevas dentro.",
  "No hay pausa. No hay tregua. No hay excusa.",
  "El gym: mi santuario, mi campo de batalla, mi hogar.",
  "Haz más series de las que planeaste. Rompe tus propios límites.",
  "El músculo que no duele, no creció.",
  "No le temas al fracaso. Témele al no haberlo intentado.",
  "Cuando creas que no puedes, recuerda por qué empezaste.",
  "Tu cuerpo es el resultado de todas tus decisiones.",
  "Si el gym fuera fácil, todos estarían mamados.",
  "La grandeza no es cómoda. La comodidad no es grande.",
  "Entrena callado. Tus resultados hablarán por ti.",
  "El gym: el único lugar donde fracasar es avanzar.",
  "Sin dolor no hay mejora.",
  "El mejor compañero de gym es el espejo.",
  "Se constante. El resto llega solo.",
  "La barra no pregunta, exige.",
  "Haz que tus pesas sientan miedo.",
  "No le pongas límites a lo que puedes lograr.",
  "Entrena con el fuego de quien quiere cambiar su vida.",
  "La disciplina es el hilo que teje los sueños.",
  "Nadie te regala nada en el gym. Todo se gana.",
  "Donde termina tu mente, empieza tu corazón.",
  "Conviértete en el reflejo de tu esfuerzo.",
  "La barra espera. No la decepciones.",
  "Hazlo por el que serás mañana.",
  "Cada cicatriz en la mano es una medalla de batalla.",
  "Que el dolor sea tu guía, no tu enemigo.",
  "Lo que piensas, lo creas. Lo que sudas, lo ganas.",
  "Entrenar es mi forma de decirle al mundo que no me rindo.",
  "No descanses hasta estar orgulloso.",
  "Vive en el gym. Sobrevive afuera.",
  "Haz de la disciplina tu zona de confort.",
  "El hombre más fuerte no es el que más levanta, sino el que más se levanta.",
  "Préndele fuego a la pereza. ¡Carga!",
  "Hasta la última gota de sudor cuenta.",
  "Lo que no te mata, te hace más fuerte. Lo que te duele, te hace más grande.",
  "Naciste para cargar. No lo olvides.",
  "El gym no es moda, es necesidad.",
  "Lo que haces hoy, mañana es tu prueba.",
  "Cada día es un PR Day si te esfuerzas.",
  "No hay límite para quien tiene hambre de grandeza.",
  "Transforma el sudor en combustible.",
  "En el gym te encuentras a ti mismo. Y a veces, te pierdes para volver más fuerte.",
  "Desafía a la gravedad cada día. Ella siempre pierde.",
  "El que se rinde nunca gana. El que gana nunca se rinde.",
  "Hazlo por ti. Por tu mejor versión.",
  "Los únicos pesos que cargas son los que tú decides levantar.",
  "Si entrenas con miedo, no creces. Si entrenas con respeto, evolucionas.",
  "Dale amor a tu cuerpo. Él te lo devolverá en fuerza.",
  "Cada día es una nueva batalla. Sal a ganar.",
  "El gimnasio no es para los que quieren, es para los que pueden soportar.",
  "La próxima repetición es la más importante.",
  "Las pesas no perdonan al que miente.",
  "Las excusas no queman calorías.",
  "Cuando tu cuerpo gime, tu mente ruge.",
  "Carga lo que puedas. Mañana carga lo que hoy no podías.",
  "Sé el dueño de tu destino. Toma las riendas de tu físico.",
  "El gym es mi droga. Soy adicto al progreso.",
  "No hay límite para quien no se rinde.",
  "Si entrenas duro, el universo conspira a tu favor.",
  "Sueña con el press. Despierta con el press. Vive para el press.",
  "Dale a tu cuerpo razones para estar orgulloso.",
  "Cada imagen del espejo es un reflejo de tus decisiones.",
  "Si no estás dispuesto a sufrir, no estás listo para ganar.",
  "Respira profundo. Agarra la barra. Vuela.",
  "El gym es el arte de esculpir el cuerpo con dolor y sudor.",
  "Un guerrero no se queja. Se levanta y carga.",
  "Donde las excusas terminan, el músculo empieza.",
  "Sé más terco que tus excusas.",
  "El peso del arrepentimiento es más pesado que cualquier barra.",
  "Hacen falta 21 días para crear un hábito. Pero solo 1 para empezar.",
  "El gym es mi psicólogo. La barra, mi terapeuta.",
  "La única persona a la que debes superar eres tú mismo.",
  "El gym te da lo que le das. Nada más, nada menos.",
  "Despierta al guerrero que llevas dentro cada mañana.",
  "No preguntes cuánto falta. Pregunta cuánto más puedes.",
  "Cuida tu cuerpo. Es el único lugar que tienes para vivir.",
  "No escondas el dolor. Abrázalo. Es señal de que estás creciendo.",
  "El camino del hierro es solitario, pero los resultados hablan por sí solos.",
  "No hay atajos en el camino hacia la grandeza.",
  "El gym está abierto para todos. Pero solo se quedan los valientes.",
  "Cada repetición es una promesa que te haces a ti mismo.",
  "Haz que la barra se arrepienta de haberte conocido.",
  "El sudor es mi perfume favorito.",
  "No corras del dolor. Correr del dolor es correr del crecimiento.",
  "Siempre hay una repetición más. Encuéntrala.",
  "La perseverancia es el músculo más importante.",
  "El mejor momento del día es cuando terminas y sabes que lo diste todo.",
  "No existe el fracaso en el gym. Existen datos para mejorar.",
  "Conviértete en un depredador de metas.",
  "No confundas movimiento con progreso. Cada rep debe tener intención.",
  "La calidad de tu esfuerzo determina la calidad de tu resultado.",
  "Enfócate. La barra no espera a los distraídos.",
  "Sangre, sudor y respeto. Los ingredientes del éxito en el gym.",
  "Más que un físico, construyes un carácter de acero.",
  "Camina con la seguridad de quien se gana la vida en el gym.",
  "El gimnasio no te da alas. Te enseña a volar sin ellas.",
  "Cada vez que entras al gym, le dices al mundo que no te conformas.",
  "El músculo más importante es el corazón.",
  "La disciplina es el puente entre las metas y los logros.",
  "La auténtica belleza está en la fuerza interior.",
  "La barra te habla. Aprende a escucharla.",
  "No busques resultados rápidos. Busca resultados permanentes.",
  "La consistencia transforma lo ordinario en extraordinario.",
  "El esfuerzo no se negocia.",
  "No le temas a levantar pesado. Témele a no intentarlo.",
  "Si vas a soñar, sueña con un PR.",
  "Haz del gym tu campo de batalla personal.",
  "No te detengas cuando estés cansado. Detente cuando hayas terminado.",
  "Las agujetas son poemas escritos por tus músculos.",
  "Sé un león en un mundo de ovejas.",
  "El gym me salvó la vida. Ahora la domina.",
  "El único milagro en el gym es la constancia.",
  "Cuando quieres rendirte, recuerda por qué empezaste.",
  "Haz del esfuerzo tu hábito y del éxito tu consecuencia.",
  "No existe el dolor, existe la incomodidad del progreso.",
  "El gimnasio te enseña a caer y levantarte. Literalmente.",
  "Cada PR es un recordatorio de que eres capaz de más.",
  "Hoy no es día de descanso. El descanso se gana.",
  "Sigue cargando. Tu futuro yo te lo agradecerá.",
  "No dejes para mañana la serie que puedes hacer hoy.",
  "Tus excusas no tienen poder aquí.",
  "Haz del dolor tu aliado. Él te avisa que estás cambiando.",
  "El gym es el sitio donde el silencio grita resultados.",
  "Rompe tus propias barreras. Una rep a la vez.",
  "El mejor accesorio del gym es la actitud.",
  "No entrenes por apariencia. Entrena por fortaleza mental.",
  "Cuando la mente dice basta, el corazón dice una más.",
  "Domina tu respiración. Controla tu carga. Gobierna tu destino.",
  "El gym es el único lugar donde levantar más que ayer es motivo de orgullo.",
  "Mide tu éxito en repeticiones, no en likes.",
  "El dolor compartido es más llevadero. Por eso entrenamos juntos.",
  "No hay excusas, solo resultados.",
  "Que tu sudor alimente tus sueños.",
  "Cada serie es una página de tu historia. Hazla épica.",
  "La barra no miente, el espejo tampoco.",
  "Sé la mejor versión de ti. Un día a la vez. Una serie a la vez.",
  "Respeta el proceso. Conviértete en la tormenta.",
  "El gym es un templo. Entra con humildad. Sal con grandeza.",
  "Tu determinación es más pesada que cualquier barra.",
  "Entrenar es mi manera de demostrarme que soy imparable.",
  "Si un músculo no arde, no está trabajando.",
  "No esperes resultados diferentes haciendo siempre lo mismo. Progresa.",
  "Un cuerpo bien entrenado es la mejor armadura.",
];
