export interface Phrase {
  text: string;
  category: string;
}

export interface PhraseCategory {
  key: string;
  label: string;
  emoji: string;
  color: string;
  phrases: string[];
}

export const PHRASE_CATEGORIES: PhraseCategory[] = [
  {
    key: "aproximacion_generica",
    label: "Aproximación en frío — Genéricas",
    emoji: "🔥",
    color: "#be0b3c",
    phrases: [
      "Hola, sé que es súper aleatorio, pero te vi pasar y tenía que venir a saludarte o me iba a arrepentir. Soy Kevin.",
      "Disculpa, tengo algo de prisa, pero me llamaste muchísimo la atención. ¿Cómo te llamas?",
      "Hola, no suelo hacer esto en la calle, pero me pareció que tienes un estilo increíble y quería decírtelo.",
      "Perdona que te interrumpa un segundo, solo quería decirte que tienes una energía súper interesante.",
      "Hola, solo tengo un minuto, pero no quería quedarme con la duda de conocerte.",
      "Sé que estás en lo tuyo, pero me pareciste muy atractiva y tenía que acercarme a comprobarlo.",
      "Perdona, te vi desde la otra esquina y pensé: 'tengo que ir a averiguar quién es'.",
      "Hola, prometo no quitarte mucho tiempo. Solo quería presentarme, soy Kevin.",
      "Disculpa, me acabo de cruzar contigo y mi instinto me dijo que debía hablarte.",
      "Hola, me encantó tu vibra. ¿Eres de por aquí o solo estás de paso?",
    ],
  },
  {
    key: "aproximacion_situacional",
    label: "Aproximación situacional",
    emoji: "🎯",
    color: "#f97316",
    phrases: [
      "Hola, qué increíble energía tiene tu perro. Me encantan, yo tengo dos que son igual de intensos. ¿Cómo se llama?",
      "Te vi dudando con el menú. Si te sirve de algo, el café de aquí te salva el día.",
      "Caminas con una prisa que parece que vas a cerrar el negocio del siglo. Me dio curiosidad saludarte.",
      "Te he visto entrenando un par de veces, tienes una disciplina que destaca. Tenía que saludarte.",
      "Perdona, me llamaron mucho la atención tus lentes/zapatos. Tienes muy buen gusto.",
      "Con este sol se antoja estar en la playa, no caminando por aquí, ¿verdad? Soy Kevin.",
      "Tienes cara de que estás explorando la ciudad buscando un buen lugar. ¿Me equivoco?",
      "Es raro ver a alguien tan concentrada hoy en día. ¿Está bueno lo que lees?",
      "Las filas son aburridas, pero al menos la vista de este lado mejoró. Hola, soy Kevin.",
      "Te veo súper concentrada eligiendo. ¿Tienes el secreto para escoger siempre lo mejor?",
    ],
  },
  {
    key: "banter",
    label: "Tonteo directo y juguetón (Banter)",
    emoji: "😏",
    color: "#ec4899",
    phrases: [
      "No sé si eres mi tipo, pero definitivamente me estás haciendo dudar.",
      "Voy a necesitar que me devuelvas la atención que me acabas de robar.",
      "Si fueras tan buena persona como aparentas, no me estarías mirando así.",
      "Tengo la sospecha de que eres un problema, pero me encantan los problemas.",
      "No te emociones, pero me estás empezando a caer mejor de lo esperado.",
      "Te daría la razón, pero entonces los dos estaríamos equivocados.",
      "Si sigues retándome así, voy a terminar invitándote a salir solo para ganarte.",
      "Tienes esa cara de inocente que no me creo ni por un segundo.",
      "Voy a tener que ponerte límites, estás agarrando demasiada confianza.",
      "Eres peligrosamente divertida, eso no es una buena combinación para mí.",
      "Me gusta tu actitud, pero no te acostumbres a que te lo diga.",
      "Siento que me vas a dar muchos dolores de cabeza, y curiosamente no me importa.",
      "Estás a dos sonrisas de que te invite un trago y a tres de que me enamore.",
      "Si fueras un deporte, definitivamente serías de riesgo extremo.",
      "Admito que me ganas en sarcasmo, y eso es mucho decir.",
      "Me encanta cómo intentas hacerte la seria cuando por dentro te estás riendo.",
      "Eres un 10, pero sospecho que tienes un carácter terrible.",
      "No me mires así, sé exactamente lo que estás pensando.",
      "Tenemos que dejar de estar de acuerdo en todo, está perdiendo la gracia.",
      "Si pasamos más tiempo juntos, alguno de los dos va a terminar perdiendo la cabeza.",
    ],
  },
  {
    key: "social",
    label: "En un evento social o de fiesta",
    emoji: "🎉",
    color: "#a855f7",
    phrases: [
      "Es difícil mantener una conversación normal con esa sonrisa tuya distrayéndome.",
      "De toda la gente aquí, eres la única con la que me interesa cruzar más de dos palabras.",
      "Tienes una forma de mirar que hace que el resto de la habitación desaparezca.",
      "Siento que podríamos escaparnos de aquí ahora mismo y la noche sería diez veces mejor.",
      "Me gusta la tranquilidad que transmites en medio de tanto caos.",
      "Tú y yo parecemos ser los únicos que estamos prestando atención a la buena música.",
      "Si me hubieran dicho que iba a conocer a alguien con tu vibra hoy, habría llegado más temprano.",
      "Te mueves con una seguridad que es imposible no notar.",
      "No soy mucho de quedarme hasta tarde, pero contigo creo que haré una excepción.",
      "Hay algo en la forma en que interactúas con los demás que te hace destacar sin esfuerzo.",
      "Pareces el tipo de persona que siempre sabe cómo hacer que un momento aburrido sea divertido.",
      "Apostaría a que eres el alma de la fiesta, aunque ahora estés intentando pasar desapercibida.",
      "Tienes ese tipo de elegancia que no se puede comprar ni fingir.",
      "Cualquiera que te vea desde lejos sabe que hay una historia interesante detrás de esa mirada.",
      "Estaba a punto de irme, pero entonces te vi y cambié de planes.",
      "Me gusta que no intentas impresionar a nadie, simplemente eres tú y eso basta.",
      "Tienes una risa que podría alegrarle el día a cualquiera.",
      "Eres la pausa perfecta en medio de una noche demasiado acelerada.",
      "Siento que me vas a convencer de hacer alguna locura antes de que termine la noche.",
      "Debería estar hablando con más gente, pero contigo la plática está demasiado buena.",
    ],
  },
  {
    key: "profunda",
    label: "Durante una conversación profunda o un café",
    emoji: "☕",
    color: "#8b5cf6",
    phrases: [
      "Me encanta tu forma de ver el mundo, es tan distinta a lo que suelo escuchar.",
      "Podría pasar horas escuchándote hablar y no me aburriría un segundo.",
      "Tienes una mente hermosa, hay mucha claridad en todo lo que dices.",
      "Es increíble lo fácil que es hablar de cosas reales contigo, sin máscaras.",
      "Me haces cuestionarme mis propias ideas, y eso me fascina.",
      "Hay una sensibilidad en ti que intentas ocultar, pero se nota en cómo hablas.",
      "Tus palabras tienen peso, se nota que piensas antes de hablar.",
      "Me gusta que no te conformas con lo superficial, siempre buscas el porqué de las cosas.",
      "Es un privilegio conocer este lado tuyo que no todos llegan a ver.",
      "Tienes un alma vieja, hay mucha sabiduría en tus experiencias.",
      "Cuando hablas de lo que te apasiona, tus ojos brillan de una manera única.",
      "Nunca había conocido a alguien que pudiera entender exactamente lo que quiero decir con tan pocas palabras.",
      "Eres de esas raras personas con las que el silencio es cómodo, no incómodo.",
      "Me gusta la honestidad brutal con la que te manejas en la vida.",
      "Tienes una madurez emocional que resulta increíblemente atractiva.",
      "La forma en que procesas tus emociones habla mucho de lo fuerte que eres.",
      "Cada vez que creo que ya te entendí, me sorprendes con una perspectiva nueva.",
      "Aprecio mucho que seas tan genuina en un mundo lleno de apariencias.",
      "Hablar contigo es como leer un buen libro del que no quieres que se acabe el capítulo.",
      "Gracias por ser el tipo de persona con la que se puede ser vulnerable.",
    ],
  },
  {
    key: "gym",
    label: "En el gimnasio o entrenando",
    emoji: "💪",
    color: "#22c55e",
    phrases: [
      "Es raro ver a alguien aquí que se tome el entrenamiento tan en serio. Respeto eso.",
      "Esa rutina se ve intensa, tienes una disciplina que ya quisieran muchos.",
      "Prometo no interrumpirte mucho, pero tu técnica en ese ejercicio es impecable.",
      "Hay algo muy atractivo en verte enfocada al cien por ciento en tus metas.",
      "Siempre que te veo aquí estás dando el máximo, es muy motivador.",
      "Se nota que no vienes a perder el tiempo, esa mentalidad me gusta.",
      "Casi me desconcentras de mi serie de pesas con esa energía que traes hoy.",
      "No cualquiera aguanta ese ritmo, definitivamente estás a otro nivel.",
      "Me encanta que no le tienes miedo a levantar pesado.",
      "Verte entrenar me hace darme cuenta de que necesito esforzarme el doble.",
      "Tienes esa mirada de concentración que dice 'no me hablen', pero me arriesgué igual.",
      "Es refrescante cruzarse con alguien que realmente disfruta el proceso y no solo busca la foto.",
      "Si le pones esa misma intensidad a todo en la vida, debes ser imparable.",
      "Haces que una rutina súper difícil se vea fácil.",
      "Esa determinación tuya es más atractiva que cualquier otra cosa en este lugar.",
      "Tenemos que entrenar juntos un día, creo que haríamos un buen equipo.",
      "Admiro a la gente que viene, hace su trabajo sin excusas y se va. Tú eres de esas.",
      "Tienes una fuerza física y mental que se nota a kilómetros.",
      "Me gusta que compites contigo misma, esa es la verdadera actitud.",
      "Después de esa serie, te mereces el resto del gimnasio solo para ti.",
    ],
  },
  {
    key: "negocios",
    label: "Negocios, emprendimiento o proyectos",
    emoji: "💼",
    color: "#3b82f6",
    phrases: [
      "Se nota que tienes mentalidad de constructora; no solo planeas, ejecutas.",
      "Es raro encontrar a alguien con tu nivel de ambición; definitivamente sabes negociar.",
      "Me gusta la visión a largo plazo que tienes, piensas como una verdadera estratega.",
      "Hablar de proyecciones y metas contigo resulta más interesante que cualquier otra charla.",
      "Tienes ese fuego interno de alguien que no se conforma con proyectos pequeños.",
      "Admiro la forma en que resuelves los problemas, tienes mente analítica.",
      "El nivel de detalle que pones en tu trabajo demuestra el compromiso que tienes con el éxito.",
      "Haces que cerrar un trato o planificar un proyecto parezca un arte.",
      "Esa seguridad que proyectas en los negocios es extremadamente cautivadora.",
      "Me gusta que tienes claro tu valor en el mercado y no dejas que nadie lo baje.",
      "Se necesita carácter para liderar y tú tienes de sobra.",
      "Tu capacidad de organización es impresionante; todo tiene estructura en tu mente.",
      "Me fascina que puedas hablar de métricas y crecimiento sin perder esa calidez humana.",
      "Tienes una ética de trabajo que inspira a cualquiera a dar más.",
      "Si seguimos compartiendo ideas así, vamos a terminar creando un imperio juntos.",
      "Es un respiro encontrar a alguien que entiende la diferencia entre estar ocupado y ser productivo.",
      "Tienes talento para ver oportunidades de desarrollo donde otros solo ven terrenos vacíos.",
      "Me gusta cómo asumes los riesgos, de forma calculada y sin miedo.",
      "Haces que la presión del trabajo se sienta como un reto divertido.",
      "Con esa determinación, estoy seguro de que cualquier marca o proyecto que toques será un éxito.",
    ],
  },
  {
    key: "mascotas",
    label: "Paseando perros o hablando de mascotas",
    emoji: "🐕",
    color: "#f59e0b",
    phrases: [
      "Se necesita carácter firme para educar bien a un perro, y tú definitivamente lo tienes.",
      "Me encanta ver el respeto que tu perro te tiene, habla mucho de tu liderazgo.",
      "Hay que tener una energía muy especial para que perros con tanto carácter te hagan caso así.",
      "Es increíble la paciencia que demuestras al enseñarle cosas nuevas, es una gran cualidad.",
      "Verte jugar y conectar con tu mascota me dice todo lo que necesito saber sobre tu corazón.",
      "Me gusta que cuidas de la salud y nutrición de tu perro como si fuera un atleta.",
      "Alguien que protege a los animales con tanta lealtad es alguien en quien confiar.",
      "No cualquiera sabe cómo ganarse a un perro fuerte, pero tú tienes un don.",
      "Esa autoridad tranquila que usas para dar comandos es impresionantemente atractiva.",
      "Me da la impresión de que tú y tu perro hacen el equipo perfecto para cualquier aventura.",
      "Es fascinante cómo puedes ser tan dulce y a la vez mantener tanta disciplina con él.",
      "A los perros no se les puede engañar con malas energías, y el tuyo te adora.",
      "El nivel de compromiso que tienes con el bienestar de tu mascota es admirable.",
      "Me gusta que no te molesta ensuciarte un poco si significa que él la pase bien.",
      "Cualquier persona que se preocupe tanto por un ser vivo ya tiene mi respeto absoluto.",
      "Me encanta que tu perro tiene tu misma vibra: tranquilo, seguro, pero imponente.",
      "Haces que entrenar a un animal parezca fácil, aunque los dos sabemos que requiere constancia.",
      "Verte caminar con él transmite mucha seguridad y paz.",
      "Creo que mis perros aprobarían totalmente a la dueña del tuyo.",
      "Tienes ese instinto protector que te hace ver genial cuando estás a cargo.",
    ],
  },
  {
    key: "futbol",
    label: "En la cancha, fútbol o viendo un partido",
    emoji: "⚽",
    color: "#10b981",
    phrases: [
      "Tienes una agresividad deportiva en la cancha que me dejó sin palabras.",
      "Me gusta que no arrugas en ningún partido, vas a todas con todo.",
      "Esa visión de juego que tienes es mejor que la de muchos que conozco.",
      "Cuando te pones la camiseta, te transformas; me encanta esa actitud ganadora.",
      "Jugar en el mismo equipo que tú hace que todo fluya mucho mejor.",
      "Gritas los goles con una pasión que es casi imposible no contagiarme.",
      "Se nota que llevas el fútbol en la sangre, tienes un toque diferente.",
      "Ese espíritu de compañerismo que muestras en la cancha dice mucho de cómo eres afuera de ella.",
      "No esperaba verte dominar así en un partido de tanta intensidad.",
      "Ver un partido en el estadio contigo y sentir cómo vives la hinchada es una experiencia aparte.",
      "Me encanta que analizas el juego, no solo lo miras por mirar.",
      "Tuviste garra en cada jugada, mis respetos totales por ese esfuerzo.",
      "Tienes esa mentalidad de no dar ningún balón por perdido que es súper atractiva.",
      "Con esa técnica que demostraste hoy, ya te ganaste tu puesto fijo de titular.",
      "Me gusta tu forma de competir: vas fuerte, pero siempre con lealtad.",
      "Casi me olvido de seguir el partido por quedarme viendo cómo celebrabas ese gol.",
      "Eres de las pocas personas con las que me disfrutaría un campeonato completo bajo el sol.",
      "Tienes más aguante físico que la mitad de los que estaban corriendo hoy.",
      "Saber que disfrutas de este deporte tanto como yo suma muchísimos puntos.",
      "La próxima vez que juguemos, te exijo que estés en mi equipo para asegurar la victoria.",
    ],
  },
  {
    key: "comida",
    label: "Comida, salidas informales o descubriendo un buen plato",
    emoji: "🍕",
    color: "#ef4444",
    phrases: [
      "Me fascina que puedas disfrutar de una buena parrillada sin estar contando las calorías todo el rato.",
      "Alguien que sabe apreciar un buen encebollado de fin de semana es alguien de mi equipo.",
      "Tienes un paladar exigente, pero a la vez disfrutas de los placeres simples; esa combinación es genial.",
      "Me encanta la cara de felicidad que pones cuando llega tu plato favorito a la mesa.",
      "Comer ceviche frente al mar contigo hace que el plato sepa cien veces mejor.",
      "Es un alivio salir con alguien que no tiene problema en comerse una buena hamburguesa con papas.",
      "Haces que una simple cena informal se sienta como el mejor evento de la semana.",
      "La forma en la que pruebas la comida antes de decir si te gusta o no es un detalle muy tuyo.",
      "Me gusta que disfrutas explorar huariques y lugares de comida china sin complicaciones.",
      "Contigo cualquier salida a comer termina siendo una anécdota súper divertida.",
      "Tienes el superpoder de hacerme reír incluso cuando tengo la boca llena.",
      "Admiro que no necesitas manteles largos para disfrutar de la buena sazón.",
      "Compartir una buena porción de pizza contigo hablando de la vida es mi nuevo plan favorito.",
      "Ese brillo en tus ojos cuando hablan de postre confirma que tomé la decisión correcta al invitarte.",
      "Se nota la pasión que tienes por descubrir nuevos sabores, eres una catadora nata.",
      "Me gusta la autenticidad con la que disfrutas cada bocado; cero pretensiones.",
      "Eres de las pocas personas con las que no me importa compartir la última rebanada.",
      "Tener una buena charla frente a unos buenos cortes de carne asada no tiene precio si es contigo.",
      "Haces de la hora de la comida un ritual de pura buena vibra.",
      "Tu compañía es el mejor condimento que le podía pedir a este plato.",
    ],
  },
  {
    key: "viajes",
    label: "Viajando o explorando la ciudad",
    emoji: "✈️",
    color: "#06b6d4",
    phrases: [
      "Tienes un instinto natural para la orientación en ciudades nuevas que me deja tranquilo.",
      "Me gusta que no te asusta caminar horas si eso significa encontrar el mejor rincón del lugar.",
      "Ver cómo te maravillas con la arquitectura de los centros históricos me encanta.",
      "Siento que podríamos cruzar fronteras juntos y nunca nos faltaría tema de conversación.",
      "Haces que explorar lugares desconocidos se sienta seguro y emocionante a la vez.",
      "Si logras que hasta la vista desde el dron se vea menos interesante que tú, estás haciendo las cosas bien.",
      "Tienes alma de aventurera; te adaptas a la arena de la playa igual de bien que al frío de la ciudad.",
      "Tus fotos no le hacen justicia a la forma real en la que tus ojos ven los paisajes.",
      "Me encanta que estás dispuesta a probar costumbres nuevas sin pensarlo dos veces.",
      "Encontrar un buen compañero de viaje es difícil, pero creo que contigo me gané la lotería.",
      "Esa curiosidad constante que tienes por la cultura local es muy tuya.",
      "Contigo un mapa es innecesario, perderme a tu lado ya es un buen plan.",
      "Haces que cada lugar nuevo que pisamos tenga un recuerdo imborrable.",
      "Me gusta que disfrutas del viaje sin estar pendiente de subirlo todo a las redes.",
      "La energía que le pones a descubrir nuevos rincones es súper estimulante.",
      "Tienes la capacidad de hacer que un simple paseo parezca una escena de película.",
      "Ver cómo interactúas con la gente local muestra tu tremenda calidad humana.",
      "Eres la compañía perfecta para armar maletas sin pensarlo demasiado.",
      "Contigo los destinos no importan tanto como el trayecto en sí.",
      "Siento que podríamos darle la vuelta al mundo y seguiríamos queriendo descubrir más juntos.",
    ],
  },
  {
    key: "ruta",
    label: "Durante un viaje largo o en ruta",
    emoji: "🚗",
    color: "#6366f1",
    phrases: [
      "Manejar durante horas se hace corto cuando la copiloto tiene tus temas de conversación.",
      "Me gusta tu gusto musical; tus playlists salvan cualquier tramo largo en carretera.",
      "Hay algo en ver el paisaje por la ventana del carro mientras platicamos que es perfecto.",
      "Tienes una tranquilidad que hace que hasta el tráfico más pesado se vuelva tolerable.",
      "Me encanta que respetas los silencios, no siempre necesitamos hablar para estar cómodos en la ruta.",
      "Estar en el auto conduciendo durante horas me parecía pesado hasta que empezaste a hablar.",
      "Ver cómo te quedas dormida en el asiento del copiloto me da muchísima ternura, no te voy a mentir.",
      "Tienes la magia de hacer que una carretera aburrida se vuelva mi parte favorita del día.",
      "Esa mirada tuya hacia la nada, viendo pasar todo allá afuera, esconde muchos pensamientos que quiero conocer.",
      "Podría manejar toda la noche si eso significa seguir escuchando tu risa de fondo.",
      "Me gusta que no te importa si nos desviamos un poco del camino original.",
      "Se nota que disfrutas de viajar cruzando el país, tienes alma para la carretera.",
      "Eres de las pocas personas que no se queja del tiempo de viaje; valoras el trayecto.",
      "Compartir un café de ruta contigo vale más que ir al mejor restaurante de la ciudad.",
      "El paisaje es impresionante, pero confieso que por el espejo retrovisor la vista es mejor.",
      "Tienes una forma muy peculiar de hacerme olvidar cuántos kilómetros nos faltan para llegar.",
      "Me gusta la química que tenemos incluso cuando solo cantamos a todo pulmón.",
      "Si hay algo mejor que la brisa entrando por la ventana, es verte disfrutarla.",
      "Haces que la cabina del carro se sienta como el mejor lugar para hablar de la vida.",
      "Este viaje no habría sido ni la mitad de bueno si no estuvieras aquí al lado.",
    ],
  },
  {
    key: "buenas_noches",
    label: "Despedirse para dormir",
    emoji: "🌙",
    color: "#0ea5e9",
    phrases: [
      "Me la pasé genial hoy. Que descanses, hablamos mañana.",
      "Fue una buena charla. Ya me toca desconectar el cerebro. Buenas noches.",
      "Espero que duermas bien. Mañana seguimos con esta conversación.",
      "Ya me rindo por hoy, el cansancio ganó. Que descanses, te escribo mañana.",
      "Me toca apagar el sistema. Que tengas buena noche.",
      "Hoy fue un día pesado, pero me encantó cruzar palabras contigo para cerrarlo. Descansa.",
      "Me voy a dormir antes de que el cansancio me haga decir tonterías. Buenas noches.",
      "Descansa. Trata de no soñar conmigo, que luego no te quieres despertar.",
      "Fue un gusto hablar contigo hoy. Que duermas súper bien.",
      "Ya voy a dejar el celular lejos. Descansa y que mañana sea un buen día para ti.",
      "Si sigues haciéndome reír no voy a dormir nunca. Buenas noches.",
      "Qué buena vibra me dejas para terminar el día. Que descanses.",
      "Me desconecto. Guarda energía que mañana la vas a necesitar.",
      "Duerme bien. Yo intentaré hacer lo mismo si mi mente me deja de dar vueltas.",
      "Ha sido un placer, pero mi cama me está reclamando a gritos. Buenas noches.",
      "Te dejo para que descanses. Fue genial coincidir hoy.",
      "Mañana te sigo ganando en esta discusión. Que descanses.",
      "Que tengas buena noche. Carga pilas que mañana tienes cosas importantes que hacer.",
      "Me voy a dormir con una buena sensación hoy. Descansa.",
      "Voy a cerrar los ojos antes de que me cuentes otra historia y me desvele. ¡Buenas noches!",
    ],
  },
];

export interface Principle {
  num: number;
  title: string;
  text: string;
  example?: string;
}

export const PRINCIPLES: Principle[] = [
  {
    num: 1,
    title: "La regla del 90/10 (Entrega vs. Contenido)",
    text: "Las palabras que usas solo importan un 10%. El 90% restante es tu lenguaje corporal. Dilo con un tono de voz calmado, manteniendo contacto visual relajado y haciendo pausas. Una frase muy simple, dicha con la postura y la mirada correctas, es mil veces más poderosa que la frase más ingeniosa dicha con nerviosismo o prisa.",
  },
  {
    num: 2,
    title: "El 'Gancho' de transición",
    text: "Una frase de acercamiento no debe ser un callejón sin salida. Después de decirle algo validante, termínalo inmediatamente con una pregunta abierta para que ella invierta en la conversación.",
    example: "Me atrae la forma en que piensas... ¿Siempre analizas así los detalles o es deformación profesional?",
  },
  {
    num: 3,
    title: "Especificidad observacional",
    text: "Adapta cualquier frase prefabricada a algo que notes de ella en ese instante exacto. Si notas un rasgo particular de su estilo, cómo camina, su actitud al cerrar un trato, o cómo interactúa con su perro en el parque, intégralo. La especificidad demuestra atención real, y la autenticidad desarma cualquier barrera.",
  },
  {
    num: 4,
    title: "Independencia del Resultado (El poder del desapego)",
    text: "El mayor error es acercarte proyectando que necesitas que la interacción salga bien o que debes conseguir su número a toda costa. Esa necesidad genera ansiedad y se nota a kilómetros. La mentalidad correcta: 'Voy a acercarme para ver si esta persona es tan interesante como aparenta'. Si ella es cortante o no muestra interés, te despides amablemente y sigues tu camino. Esa tranquilidad te hace ver increíblemente seguro.",
  },
  {
    num: 5,
    title: "Calibración (Leer la temperatura)",
    text: "Tu trabajo no termina al decir la frase; ahí apenas empieza. Tienes que leer su lenguaje corporal para saber cómo reaccionar. Si acelera: voltea todo su cuerpo hacia ti, mantiene el contacto visual y te hace preguntas de vuelta, sigue invirtiendo en la charla. Si frena: te da respuestas cortas de una palabra, mira su teléfono o su cuerpo apunta hacia otro lado, córtalo tú primero diciendo: 'Bueno, te dejo para que sigas en lo tuyo, un gusto conocerte'.",
  },
  {
    num: 6,
    title: "Dominar el Silencio (Tensión subcomunicada)",
    text: "Es común ponerse nervioso cuando hay un silencio e intentar llenarlo rápidamente haciendo preguntas aburridas (modo entrevista). Aprende a disfrutar las pausas. Después de decirle un cumplido genuino (ej. 'Hay algo magnético en cómo eres'), no digas nada por 2 o 3 segundos. Solo sostén su mirada con una media sonrisa. Ese silencio crea una tensión emocional altísima.",
  },
  {
    num: 7,
    title: "El 'Tira y Afloja' (Push & Pull)",
    text: "Si solo usas frases de validación y halagos, puedes parecer demasiado complaciente, aburrido o predecible. Las interacciones interesantes necesitan un poco de fricción y juego. Intercala la validación con un poco de reto.",
    example: "Me encanta tu energía (Pull/Acercamiento)... pero siento que eres un peligro y me vas a meter en problemas, mejor mantengo mi distancia (Push/Alejamiento). Esto la descoloca de manera divertida y hace que ella quiera cualificarse ante ti.",
  },
];
