-- Seed de vacunas para la app "guau"
INSERT INTO vaccines (application_id, name, group_name, vaccine_group, description, severity, contagion_type, mandatory, dose_count)
SELECT a.id, v.name, v.group_name, v.vaccine_group, v.description, v.severity, v.contagion_type, v.mandatory, v.dose_count
FROM applications a
CROSS JOIN (VALUES
  ('Hepatitis Infecciosa', 'Core', 'core', 'El adenovirus canino tipo 1 ataca el hígado, riñones y ojos. Puede causar hepatitis fulminante, falla renal y ceguera. La mortalidad es del 30% en casos severos. El "ojo azul" es una secuela típica.', 'alto', 'Contacto con orina, heces o saliva de perros infectados. El virus resiste meses en el ambiente.', true, 4),
  ('Moquillo Canino', 'Core', 'core', 'Virus altamente contagioso que ataca múltiples sistemas: respiratorio, digestivo y nervioso. Provoca fiebre, secreciones nasales, neumonía, vómitos, diarrea y convulsiones. Mortalidad del 50-80%. Los sobrevivientes pueden quedar con tics nerviosos permanentes.', 'mortal', 'Gotitas respiratorias (estornudos, tos). El virus sobrevive poco tiempo fuera del cuerpo.', true, 4),
  ('Parvovirus Canino', 'Core', 'core', 'Ataca células del intestino y médula ósea. Causa diarrea sanguinolenta severa, vómitos, deshidratación extrema y shock séptico. Mortalidad del 90% sin tratamiento. Afecta principalmente cachorros de 6-20 semanas.', 'mortal', 'Contacto fecal-oral. El virus sobrevive AÑOS en el ambiente. Altamente resistente a desinfectantes comunes.', true, 4),
  ('Rabia', 'Core', 'core', 'Virus que ataca el sistema nervioso central. Una vez que aparecen síntomas clínicos, es 100% MORTAL en todas las especies. Se transmite a humanos (zoonosis). Los síntomas incluyen cambios de comportamiento, agresividad, parálisis y muerte.', 'mortal', 'Mordedura de animal infectado. La saliva contiene el virus. Todos los mamíferos son susceptibles.', true, 2),
  ('Tos de las Perreras (Bordetella)', 'Opcional', 'optional', 'Infección respiratoria altamente contagiosa caracterizada por tos seca persistente que suena como un "graznido". Puede complicarse con neumonía en cachorros o perros inmunocomprometidos. Muy común en guarderías y pensiones.', 'medio', 'Aerosoles respiratorios. Ambientes con alta concentración de perros: pensiones, concursos, parques.', false, 3),
  ('Leptospirosis', 'Opcional', 'optional', 'Bacteria que ataca riñones e hígado. Causa fiebre, vómitos, ictericia e insuficiencia renal aguda. Es una ZOONOSIS GRAVE: puede transmitirse a humanos causando enfermedad de Weil. Más común en zonas tropicales y húmedas.', 'alto', 'Contacto con agua o tierra contaminada con orina de animales infectados (roedores, mapaches). Penetra por piel o mucosas.', false, 4),
  ('Coronavirus Canino', 'Opcional', 'optional', 'Virus intestinal que causa gastroenteritis aguda con diarrea y vómitos. Generalmente menos severo que el parvovirus pero puede ser grave en combinación con otros patógenos. Cachorros son los más afectados.', 'medio', 'Contacto fecal-oral. Altamente contagioso en criaderos y refugios.', false, 3),
  ('Enfermedad de Lyme', 'Opcional', 'optional', 'Causada por la bacteria Borrelia burgdorferi transmitida por garrapatas. Provoca fiebre, cojera intermitente, inflamación articular y daño renal crónico. Los síntomas pueden aparecer meses después de la picadura.', 'alto', 'Picadura de garrapata infectada (género Ixodes). Requiere que la garrapata esté adherida 24-48 horas.', false, 3),
  ('Influenza Canina', 'Opcional', 'optional', 'Virus de influenza H3N8 y H3N2 específicos de perros. Causa brotes de enfermedad respiratoria con tos, fiebre alta y secreción nasal purulenta. Puede progresar a neumonía hemorrágica fatal. Alta morbilidad en poblaciones no vacunadas.', 'alto', 'Gotitas respiratorias y fómites contaminados. Brotes comunes en exposiciones, pensiones y refugios.', false, 3)
) AS v(name, group_name, vaccine_group, description, severity, contagion_type, mandatory, dose_count)
WHERE a.slug = 'guau'
AND NOT EXISTS (SELECT 1 FROM vaccines WHERE name = v.name AND application_id = a.id);
